// Deterministically pregenerate every media mini-app for static hosting.
import { extname, join } from "std/path/mod.ts";
import { generatePage } from "../lib/generate.ts";
import { renderPage } from "../lib/page.ts";

const mediaDir = Deno.env.get("MEDIA_DIR") ?? "./media";
const outputDir = Deno.env.get("OUT_DIR") ?? "./dist";
const mediaBase = (Deno.env.get("MEDIA_BASE") ?? "../media").replace(/\/$/, "");
const copyMedia = Deno.env.get("COPY_MEDIA") === "1";
const buildDate = Deno.env.get("BUILD_DATE") ?? new Date(0).toISOString();
const siteBase = Deno.env.get("SITE_BASE") ?? "./";
const extensions = [
  ".mp4",
  ".webm",
  ".mov",
  ".m4v",
  ".ogv",
  ".mp3",
  ".m4a",
  ".wav",
  ".ogg",
  ".opus",
  ".aac",
];

await Deno.mkdir(outputDir, { recursive: true });
if (copyMedia) {
  await Deno.mkdir(join(outputDir, mediaBase), { recursive: true });
}
const files: string[] = [];
for await (const entry of Deno.readDir(mediaDir)) {
  if (entry.isFile && extensions.includes(extname(entry.name).toLowerCase())) {
    files.push(entry.name);
  }
}

const links: string[] = [];
for (const file of files.sort()) {
  const data = await generatePage(
    join(mediaDir, file),
    undefined,
    undefined,
    siteBase,
  );
  data.mediaPath = `${mediaBase}/${encodeURIComponent(file)}`;
  data.generatedAt = buildDate;
  await Deno.writeTextFile(
    join(outputDir, `${data.slug}.html`),
    renderPage(data),
  );
  if (copyMedia) {
    await Deno.copyFile(join(mediaDir, file), join(outputDir, mediaBase, file));
  }
  links.push(`<li><a href="${data.slug}.html">${data.title}</a></li>`);
  console.log(
    `generated ${data.slug}.html from ${file} (${data.kind}, ${
      data.durationSec.toFixed(1)
    }s)`,
  );
}

const index =
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>content-type-gen static examples</title><style>:root{color-scheme:dark}body{max-width:45rem;margin:2rem auto;padding:0 1rem;font:1rem/1.6 system-ui,sans-serif}a{color:#78b3ff}</style></head><body><main><h1>content-type-gen</h1><p>Static, deterministic media mini-apps generated by the same probe → generate → render pipeline.</p><ul>${
    links.join("")
  }</ul><section id="how"><h2>How these pages were generated</h2><p>Each mini-app was built locally from its media file. The pipeline reads metadata with <code>ffprobe</code>, derives a title, description, chapters, and transcript cues, then renders the result as a self-contained HTML page without an external AI service.</p></section></main></body></html>`;
await Deno.writeTextFile(join(outputDir, "index.html"), index);
console.log(`pregenerated ${files.length} pages into ${outputDir}/`);
